// player
export const PLAYER_STATUS_CHANGED = 'PLAYER_STATUS_CHANGED';

export const PLAYER_CONNECTED = 'PLAYER_CONNECTED';

// broadcasting
export const BITRATE_CHANGED = 'BITRATE_CHANGED';

export const CURRENT_TIME_CHANGED = 'CURRENT_TIME_CHANGED';

export const CURRENT_TIME_RESET = 'CURRENT_TIME_RESET';

// settings
export const REHYDRATE_SETTINGS = 'REHYDRATE_SETTINGS';

export const SET_SETTINGS = 'SET_SETTINGS';
