// player
export const PLAYER_STATUS_CHANGED = 'PLAYER_STATUS_CHANGED';

export const PLAYER_CONNECTED = 'PLAYER_CONNECTED';

// broadcasting
export const BITRATE_CHANGED = 'BITRATE_CHANGED';

export const CURRENT_TIME_CHANGED = 'CURRENT_TIME_CHANGED';
